New .FULL_LICENSE test
 Improve test cases
   Adjust @main.c.txt for "<filename>: ..."
   Add new test case files
   Test with full license info output
   Update .FULL_LICENSE.KEEP to get build "SUCESS"
 lintian clean changes
   Fool lintian complaining GFDL
   Update Vcs-* fields

diff --git a/test/src/Makefile b/test/src/Makefile
--- a/test/src/Makefile
+++ b/test/src/Makefile
@@ -13,9 +13,10 @@ export PATH
 LC_ALL=C.UTF-8
 export LC_ALL
 
-all: test
+all: test2
 	# If different, next line returns non-zero(=ERROR)
-	diff -u $(PWD)/../.LICENSE.KEEP $(PWD)/../.LICENSE.LOG
+	#diff -u $(PWD)/../.LICENSE.KEEP $(PWD)/../.LICENSE.LOG
+	diff -u $(PWD)/../.FULL_LICENSE.KEEP $(PWD)/../.FULL_LICENSE.LOG
 
 # Please place data from SPDX in src/dspdx/*
 spdx:
@@ -48,7 +49,7 @@ mit:
 	cd ..; src/split copyright-clean
 	rm -f ../copyright-clean
 
-test:
+test1:
 	echo $$PATH
 	echo $$PYTHONPATH
 	cd .. ;\
@@ -58,6 +59,17 @@ test:
 	echo -n '.' >&2 ;\
 	done ; echo >&2 ) | sort > $(PWD)/../.LICENSE.LOG
 	diff -u $(PWD)/../.LICENSE.KEEP $(PWD)/../.LICENSE.LOG > $(PWD)/../.LICENSE.DIFF \
+		&& echo "SUCCESS" || echo "FAIL"
+
+test2:
+	echo $$PATH
+	echo $$PYTHONPATH
+	cd .. ;\
+	(for x in $$(ls *.txt); do \
+	copyright.py $$x ; \
+	echo -n '.' >&2 ;\
+	done ; echo >&2 ) > $(PWD)/../.FULL_LICENSE.LOG
+	diff -u $(PWD)/../.FULL_LICENSE.KEEP $(PWD)/../.FULL_LICENSE.LOG > $(PWD)/../.FULL_LICENSE.DIFF \
 		&& echo "SUCCESS" || echo "FAIL"
 
 clean:
