Major reorganization of copyright.py
 * Split core part of copyright.py as checkdep5
 * Make associated changes
 * Rename functions and variables with better names
 * Refine regexs
 * Extend non-pedantic behaviors
 * Add modern autotools support
 * Refine C_COPY handling
 * Refine __AUTO_PERMISSIVE__ (re.VERBOSE needs \s for ' '
 * More MAX_*_LINES
 * Update test code
 * Remove bogus "None" output
 * Output name/apachename

test/src/Makefile now test FULL LICENSE as default

OLD OUTPUT

diff --git a/test/src/Makefile b/test/src/Makefile
--- a/test/src/Makefile
+++ b/test/src/Makefile
@@ -13,10 +13,7 @@ export PATH
 LC_ALL=C.UTF-8
 export LC_ALL
 
-all: test2
-	# If different, next line returns non-zero(=ERROR)
-	#diff -u $(PWD)/../.LICENSE.KEEP $(PWD)/../.LICENSE.LOG
-	diff -u $(PWD)/../.FULL_LICENSE.KEEP $(PWD)/../.FULL_LICENSE.LOG
+all: test
 
 # Please place data from SPDX in src/dspdx/*
 spdx:
@@ -49,31 +46,35 @@ mit:
 	cd ..; src/split copyright-clean
 	rm -f ../copyright-clean
 
-test1:
-	echo $$PATH
-	echo $$PYTHONPATH
-	cd .. ;\
-	(for x in *.txt; do \
-	printf "%s\t" "$$x" ; \
-	copyright.py -i $$x ; \
-	echo -n '.' >&2 ;\
-	done ; echo >&2 ) | sort > $(PWD)/../.LICENSE.LOG
-	diff -u $(PWD)/../.LICENSE.KEEP $(PWD)/../.LICENSE.LOG > $(PWD)/../.LICENSE.DIFF \
-		&& echo "SUCCESS" || echo "FAIL"
+test: test-dep5
 
-test2:
+test-dep5:
 	echo $$PATH
 	echo $$PYTHONPATH
 	cd .. ;\
+	: 2> $(PWD)/../.FULL_LICENSE.STDERR; \
 	(for x in $$(ls *.txt); do \
-	copyright.py $$x ; \
-	echo -n '.' >&2 ;\
-	done ; echo >&2 ) > $(PWD)/../.FULL_LICENSE.LOG
-	diff -u $(PWD)/../.FULL_LICENSE.KEEP $(PWD)/../.FULL_LICENSE.LOG > $(PWD)/../.FULL_LICENSE.DIFF \
-		&& echo "SUCCESS" || echo "FAIL"
+	echo "File: $$x " >&2; \
+	checkdep5.py $$x 2>> $(PWD)/../.FULL_LICENSE.STDERR; \
+	done ) > $(PWD)/../.FULL_LICENSE.LOG
+	diff -u $(PWD)/../.FULL_LICENSE.KEEP $(PWD)/../.FULL_LICENSE.LOG > $(PWD)/../.FULL_LICENSE.DIFF
+	# If different, above line returns non-zero(=ERROR) and exit
+	@echo "=== SUCCESS ==="
 
+test-id:
+	echo $$PATH
+	echo $$PYTHONPATH
+	cd .. ;\
+	: 2> $(PWD)/../.LICENSE.STDERR; \
+	(for x in $$(ls *.txt); do \
+	echo "File: $$x " >&2; \
+	checkdep5.py -i $$x 2>> $(PWD)/../.LICENSE.STDERR; \
+	done ) > $(PWD)/../.LICENSE.LOG
+	diff -u $(PWD)/../.LICENSE.KEEP $(PWD)/../.LICENSE.LOG > $(PWD)/../.LICENSE.DIFF
+	# If different, above line returns non-zero(=ERROR) and exit
+	@echo "=== SUCCESS ==="
 clean:
-	rm -f $(PWD)/../.LICENSE.LOG $(PWD)/../.LICENSE.DIFF
+	rm -f $(PWD)/../.LICENSE.LOG $(PWD)/../.LICENSE.DIFF $(PWD)/../.FULL_LICENSE.STDERR
 
 distclean: clean
 
